### PR TITLE
Add support for react-navigation@5

### PR DESCRIPTION
**Pull request by armenio**

### CODE REVIEW

**Comment by eriveltonelias** [comment]
Hey @armenio, thanks for your PR. I will review it as soon as possible.

**Comment by armenio** [comment]
> Hey @armenio, thanks for your PR. I will review it as soon as possible.

@eriveltonelias if any further changes are needed, let me know. I think a lot of people are waiting for these changes

**Comment by summerkiflain** [comment]
Hi @eriveltonelias, Please merge it soon, thanks.

**Review by eriveltonelias — APPROVED** [review]
thanks for your PR ❤️ ! 

I'll add a few more examples and publish it.

**Comment by summerkiflain** [comment]
@eriveltonelias can you please publish this on npm? and please let me know if there is something needed to be done on PR https://github.com/react-navigation/search-layout/pull/21

**Pull request merged**
